task: detection

num_classes: 12
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/pidray_yolo/images/train/
    ann_file: ./dataset/pidray/annotations/instances_train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 8
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/pidray_yolo/images/val/
    ann_file: ./dataset/pidray/annotations/instances_val.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 8
  num_workers: 8
  drop_last: False
